server:
  port: 8080
  shutdown: graceful # this setting makes spring boot shutdown gently
spring:
  autoconfigure:
    exclude:
  lifecycle:
    # this is the time that springboot can wait for when it got exit command
    timeout-per-shutdown-phase: 1h
  datasource:
  ### postgre ###
    url: jdbc:mysql://172.17.0.1:3306/surl_prod
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.17.0.1
      port: 6379
      password: ${custom.secret.spring.data.redis.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # in production mode, make log as false is general setting.
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    # in production mode, make log level as info is general setting.
    com.koreait.surl_project_11: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "My Site Prod"