server:
  port: 8080
spring:
  datasource:
  ### postgre ###
    url: jdbc:mysql://172.17.0.1:3306/surl_prod
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # in production mode, make log as false is general setting.
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    # in production mode, make log level as info is general setting.
    com.koreait.surl_project_11: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "My Site Prod"